export const ADD_CURRENT_USER = 'ADD_CURRENT_USER'
export const FOLLOW = "FOLLOW"
export const UNFOLLOW = "UNFOLLOW"
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
export const LOADING_CURRENT_USER = "LOADING_CURRENT_USER"
export const LOADING_FOLLOW = "LOADING_FOLLOW"
export const LOADING_UNFOLLOW = "LOADING_UNFOLLOW"